---
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24

# Text to speech
tts:
  - platform: google_translate

recorder:
  db_url: !secret mariab_addon_homeassistant_url
  purge_keep_days: 30
  exclude:
    domains:
      - media_player

group: !include groups.yaml
automation manual: !include_dir_merge_list automations
automation ui: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml

notify:
  - platform: html5
    name: HTML5Notifier
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret email_address
