---
esphome:
  name: front-bedroom-sensor

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "e9cc739163fd987bd7cab8d3269e0128"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Front-Bedroom-Sensor"
    password: !secret fallback_hotspot_password

captive_portal:

# Enable I2C interface
i2c:

# Add proprietary Bosch BSEC library for IAQ
bme680_bsec:
  address: 0x77 # Sensor is at alternative I2C address

sensor:
  - platform: bme680_bsec
    temperature:
      name: "Front bedroom temperature"
      accuracy_decimals: 2
    pressure:
      name: "Front bedroom pressure"
      accuracy_decimals: 1
    humidity:
      name: "Front bedroom humidity"
      accuracy_decimals: 1
    iaq:
      name: "Front bedroom indoor air quality"
    co2_equivalent:
      name: "Front bedroom CO2 equivalent"
    breath_voc_equivalent:
      name: "Front bedroom breath VOC equivalent"

text_sensor:
  - platform: bme680_bsec
    iaq_accuracy:
      name: "Front bedroom IAQ accuracy"
